### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'aliases.json'

### ISSUE THREAD

**Issue by bhcopeland** [chaoss/grimoirelab#175]
When running grimoirelab/installed I get 

`Exception in thread git:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_manager.py", line 98, in run
    task.execute()
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_collection.py", line 123, in execute
    es_aliases = self.select_aliases(cfg, self.backend_section)
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_collection.py", line 68, in select_aliases
    aliases = self.load_aliases_from_json(aliases_file)
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task.py", line 55, in load_aliases_from_json
    with open(aliases_json, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'aliases.json'
`

This is fixed either by running sirmordered manually or copying /aliases.json to /home/grimoirelab.

**Comment by jgbarah** [comment]
Thanks for the report and the remedy!

This is fixed in #167 so it should come in the next release of the containers...
