### ISSUE TITLE
error while creating simple dashboard using ELK and kibana

### ISSUE THREAD

**Issue by FredaPinto** [chaoss/grimoirelab#195]
Below command i am trying to execute to get kibana dashboard with git data.
**Laptop-15-bs0xx:**~$ p2o.py --enrich --index git_raw --index-enrich git -e http://localhost:9200 --no_inc --debug git https://github.com/grimoirelab/perceval.git

Output:-
2019-06-03 10:21:16,346 Debug mode activated
2019-06-03 10:21:16,346 Feeding Ocean from git (git_raw)
2019-06-03 10:21:16,354 Found version of ES instance at http://localhost:9200: 7.
2019-06-03 10:21:16,363 Error creating ES mappings {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}
2019-06-03 10:21:16,364 Mapping: 
         {
            "dynamic":true,
            "properties": {
                "data": {
                    "properties": {
                        "message": {
                            "type": "text",
                            "index": true
                        }
                    }
                }
            }
        }
        
2019-06-03 10:21:16,364 Error feeding ocean from git (https://github.com/grimoirelab/perceval.git): 400 Client Error: Bad Request for url: http://localhost:9200/git_raw/items/_mapping
Traceback (most recent call last):
  File "/home/venvs/gl/lib/python3.6/site-packages/grimoire_elk/elk.py", line 146, in feed_backend
    elastic_ocean = get_elastic(url, es_index, clean, ocean_backend, es_aliases)
  File "/home/venvs/gl/lib/python3.6/site-packages/grimoire_elk/utils.py", line 254, in get_elastic
    analyzers=analyzers, aliases=es_aliases)
  File "/home/venvs/gl/lib/python3.6/site-packages/grimoire_elk/elastic.py", line 100, in __init__
    self.create_mappings(map_dict)
  File "/home/venvs/gl/lib/python3.6/site-packages/grimoire_elk/elastic.py", line 322, in create_mappings
    res.raise_for_status()
  File "/home/venvs/gl/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:9200/git_raw/items/_mapping
2019-06-03 10:21:16,367 Done git 
2019-06-03 10:21:16,368 Backend feed completed
2019-06-03 10:21:16,375 Found version of ES instance at http://localhost:9200: 7.
2019-06-03 10:21:16,388 Can't create index http://localhost:9200/git (400)
2019-06-03 10:21:16,389 Error enriching ocean from git (https://github.com/grimoirelab/perceval.git): 
Traceback (most recent call last):
  File "/home/venvs/gl/lib/python3.6/site-packages/grimoire_elk/elk.py", line 574, in enrich_backend
    elastic_enrich = get_elastic(url, enrich_index, clean, enrich_backend, es_enrich_aliases)
  File "/home/venvs/gl/lib/python3.6/site-packages/grimoire_elk/utils.py", line 254, in get_elastic
    analyzers=analyzers, aliases=es_aliases)
  File "/home/venvs/gl/lib/python3.6/site-packages/grimoire_elk/elastic.py", line 87, in __init__
    raise ElasticWriteException()
grimoire_elk.elastic.ElasticWriteException
2019-06-03 10:21:16,389 Done git 
2019-06-03 10:21:16,389 Enrich backend completed
2019-06-03 10:21:16,389 Finished in 0.00 min

**Comment by valeriocos** [comment]
Hi @FredaPinto , thank you for reporting this issue. Which version of ELK and elasticsearch are you using ?

I tried with the following docker-compose https://github.com/chaoss/grimoirelab-sirmordred/blob/master/README.md#source-code-and-docker and the master branch of ELK, and I didn't detect any problem. Please find below the params of p2o:
```
--enrich
--index perceval_git_raw
--index-enrich perceval_git
-e https://admin:admin@localhost:9200
--no_inc
--debug
--db-host 127.0.0.1
--db-sortinghat test_sh
--db-user root
git https://github.com/chaoss/grimoirelab-perceval
```

**Comment by FredaPinto** [comment]
Hi Valerio,
The elasticsearch is 7.1.1
And i had installed grimoirelab through python library by using command pip3 install grimoirelab so it should be standard one that comes with grimoirelab 0.2.14
I can't find ELK version ,could you please guide me to check same ?

Regards,
Freda

**Comment by valeriocos** [comment]
Please try with elasticsearch 6.1.0 (recent versions are not guaranteed to work).
The grimoirelab version is enough to know the version of ELK (I thought you were using only the ELK repository). Btw, you can check the version of ELK for grimoirelab 0.2.14 at: https://github.com/chaoss/grimoirelab/commit/6a922ab56f7b6ccb6209296f91a1dc033a0d0bcc#diff-db7d281f2bc6a16ae8cd42a319150ff6R6

Cheers,
Valerio

**Comment by valeriocos** [comment]
Hi @FredaPinto , were you able to resolve this issue ?

**Comment by FredaPinto** [comment]
Hi Valerio,

Can you please guide me how to uninstall and install older elasticsearch...i searched it on google but its giving me errors.

Regards,
Freda

**Comment by valeriocos** [comment]
Sorry for the late reply, Freda. 
The error is due because the port 9200 is already in use by another process in your system.

you can check the applications using ports with: `sudo netstat -tulpn`, more info at:
https://www.cyberciti.biz/faq/unix-linux-check-if-port-is-in-use-command/

**Comment by jgbarah** [comment]
Besides, and just in case, update your grimoirelab version:

```
pip install grimoirelab --upgrade
```

Current version is 0.2.23. You can find out your version with:

```
grimoirelab --version
```

**Comment by FredaPinto** [comment]
Hi Valerio and Jesus,

Thanks for suggesting above steps but no luck error still exists.
@valeriocos--> port is not occupied i checked given command.I looked up error and installed xpack even downgraded java jdk version.
@jgbarah updated the grimioirelab version.
The error log of elasticsearch is as below:-
[2019-06-08T11:54:48,100][ERROR][o.e.b.Bootstrap          ] Exception
org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:20, legacy:false, file:/var/lib/elasticsearch/nodes/0/indices/wjnwtj4HQkSjNDmeRckFrg/_state/state-20.st]
	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:196) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:334) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.common.util.IndexFolderUpgrader.upgrade(IndexFolderUpgrader.java:90) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.common.util.IndexFolderUpgrader.upgradeIndicesIfNeeded(IndexFolderUpgrader.java:128) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:87) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.node.Node.<init>(Node.java:421) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) [elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.1.4.jar:6.1.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.1.4.jar:6.1.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) [elasticsearch-6.1.4.jar:6.1.4]
Caused by: java.io.IOException: failed to read [id:20, legacy:false, file:/var/lib/elasticsearch/nodes/0/indices/wjnwtj4HQkSjNDmeRckFrg/_state/state-20.st]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:327) ~[elasticsearch-6.1.4.jar:6.1.4]
	... 15 more
Caused by: java.lang.IllegalArgumentException: Unexpected field [mapping_version]
	at org.elasticsearch.cluster.metadata.IndexMetaData$Builder.fromXContent(IndexMetaData.java:1259) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.cluster.metadata.IndexMetaData$2.fromXContent(IndexMetaData.java:1305) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.cluster.metadata.IndexMetaData$2.fromXContent(IndexMetaData.java:1296) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:202) ~[elasticsearch-6.1.4.jar:6.1.4]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:322) ~[elasticsearch-6.1.4.jar:6.1.4]
	... 15 more

**Comment by valeriocos** [comment]
Is it possible that you have data from different ES versions (from the log above `Caused by: java.lang.IllegalArgumentException: Unexpected field [mapping_version]`) ?

**Comment by FredaPinto** [comment]
Hi valerio,

I am not sure about that but i tried again uninstalling 6.1.4 and installing 7.1.1 that works fine with url but gives error when i try to create dashboard as before.
I am checking for that error but no luck also i am trying to deploy via dockerhub the whole grimoirelab project.I will update you if that works for me.
Thank you.

Regards,
Freda Pinto

**Comment by valeriocos** [comment]
Hi @FredaPinto , any news about this issue ?  thanks :)

**Comment by FredaPinto** [comment]
Hi Valerio,

I have been trying to connect via dockerhub but facing issue with that too.
Can you check if im my input is correct,i have followed the document still facing issue.
command:-
sudo docker run -p 127.0.0.1:5601:5601     -v $(pwd)/credentials.cfg:/override.cfg     -t grimoirelab/full

output:-
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/home/freda/credentials.cfg\\\" to rootfs \\\"/var/lib/docker/overlay2/f61a4c0aebec3e91213266223248dfdc173b591df868d436c463b124fe2c90f6/merged\\\" at \\\"/var/lib/docker/overlay2/f61a4c0aebec3e91213266223248dfdc173b591df868d436c463b124fe2c90f6/merged/override.cfg\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by valeriocos** [comment]
Hi Freda,

The error should be related to the fact that the file `credentials.cfg` is missing.

Please try to create a file `credentials.cfg`, with the following content:
```
[github]
api-token = <your-github-token>
```

and then execute again:
```
sudo docker run -p 127.0.0.1:5601:5601 -v $(pwd)/credentials.cfg:/override.cfg -t grimoirelab/full
```

**Comment by GeorgLink** [comment]
@FredaPinto you seem to be determined to get a GrimoireLab dashboard to work.  :smile:

I ran into similar issues but I have been able to get a dashboard to work. I can offer a video call with you to trouble shoot issues together. Ping me at georglink@bitergia.com if you are interested.

**Comment by FredaPinto** [comment]
@valeriocos definitely will try doing this and let you know.

@GeorgLink :-thanks will reach out to you for some help :)

**Comment by valeriocos** [comment]
@FredaPinto please let us know if you need some help, or feel free to close this issue, thanks :)

**Comment by GeorgLink** [comment]
@valeriocos: I met with @FredaPinto today but we had technical issues connecting and will try to meet again tomorrow.

**Comment by valeriocos** [comment]
Hi @FredaPinto , how is it going with this issue, can we close it ?

**Comment by FredaPinto** [comment]
Hi Valerio,

I am trying different version of grimoirelab as suggested by @GeorgLink but facing different issue posted on Gitlab.
I am trying that demo grimoirelab dashboard if it goes well i will close this issue or else i would post update on older method that i tried.

Regards,
Freda

**Comment by valeriocos** [comment]
Thanks @FredaPinto , let us know if we can help you in some way.

**Comment by FredaPinto** [comment]
Hi All,
 I am closing this issue as the other solution worked finally.
Thanks to @GeorgLink for all the support and help and @valeriocos thanks a lot for your constant feedback and help.

Regards,
Freda Pinto

**Comment by valeriocos** [comment]
Great news! Thank you @FredaPinto , don't hesitate to ping us if you experience other problems.
