### ISSUE TITLE
Unable to fetch private repositories via grimoirelab/full image.

### ISSUE THREAD

**Issue by asharabu** [chaoss/grimoirelab#209]
Reopening the issue https://github.com/chaoss/grimoirelab/issues/205

Hi,

Thanks. It was working and displaying the output when we give only git and github section on projects.json.

When adding the github:repo for private repo, it is still showing the error and the repository is not showing under tab "GitHub Repositories" on kibana dashboard. Please note that commit message counts are showing for the private repo on kibana dashboard under Overview.

Please see the ebtries which I gave on projects.json

"Ashar-private": {
    "git": [
        "https://asharabu:<key>@github.com/asharabu/Testgit123"
    ],
    "github": [
        "https://github.com/asharabu/Testgit123"
    ],
    "github:repo": [
        "https://asharabu:<key>@github.com/asharabu/Testgit123"
    ]
}
The error message is getting,

2019-08-27 10:15:08,298 - grimoire_elk.elk - ERROR - Error feeding ocean from github (https://github.com/asharabu/Testgit123): 404 Client Error: Not Found for url: https://api.github.com/repos/asharabu/Testgit123
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 229, in feed_backend
ocean_backend.feed(**params)
File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 229, in feed
self.feed_items(items)
File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 245, in feed_items
for item in items:
File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 162, in fetch
for item in self.fetch_items(category, **kwargs):
File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 305, in __fetch_repo_info
raw_repo = self.client.repo()
File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 663, in repo
r = self.fetch(path)
File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 772, in fetch
response = super().fetch(url, payload, headers, method, stream, verify)
File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
raise e
File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
response.raise_for_status()
File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/asharabu/Testgit123
Collection for github:repo: finished after 00:00:04 hours

**Comment by valeriocos** [comment]
Hi @asharabu 

try with the following:

your projects.json should have this section:
```
"github:repo": [
"https://github.com/asharabu/Testgit123"
]
```

your credentials.cfg should include:
```
[github:repo]
api-token = ...
```

Please check that in the dashboard.cfg you have `github-repos = true` in the section `panels`:
```
[panels]
kibiter_time_from= "now-30y"
...
github-repos = true
```

**Comment by asharabu** [comment]
Hi,
Thanks for your update.
As you instructed we tried as below,

    "Ashar-private": {
        "git": [
            "https://asharabu:<key>@github.com/asharabu/Testgit123"
        ],
        "github": [
            "https://github.com/asharabu/Testgit123"
        ],
        "github:repo": [
            "https://github.com/asharabu/Testgit123"
        ]
    }

But still getting the below error. 

2019-08-27 15:05:24,724 - grimoire_elk.elk - ERROR - Error feeding ocean from github (https://github.com/asharabu/Testgit123): 404 Client Error: Not Found for url: https://api.github.com/repos/asharabu/Testgit123
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 229, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 229, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 245, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 162, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 305, in __fetch_repo_info
    raw_repo = self.client.repo()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 663, in repo
    r = self.fetch(path)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 772, in fetch
    response = super().fetch(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/asharabu/Testgit123
Collection for github:repo: finished after 00:00:03 hours

=====
Please note that the public repo is working for showing commit messages and Git repo URLs. But when use private repo it is showing commit messages but the github URL not showing on the tab  "GitHub Repositories"  of kibana.

**Comment by valeriocos** [comment]
Hi @asharabu,

You're welcome :)

- Have you included in the credentials.cfg the section about `[github:repo]`?
```
[github:repo]
api-token = ...
```

- Can you share your dashboards.cfg/setup.cfg?

> Please note that the public repo is working for showing commit messages and Git repo URLs. But when use private repo it is showing commit messages but the github URL not showing on the tab "GitHub Repositories" of kibana.

GitHub repositories data is not related to Git, it is fetched from the API and declared in a dedicated projects.json and dashboards.cfg section (`github:repo`).

**Comment by asharabu** [comment]
Hi,
Thanks for your update. It is working now.

There is one more issue we are seeing which is under the "Git" tab on kibana the private URL is displaying with username and key which will affect the 
![Screenshot_14](https://user-images.githubusercontent.com/42669995/63847958-7ff79280-c9ac-11e9-81c8-06423e5bc8f9.jpg)
high-security issue.

**Comment by valeriocos** [comment]
> Thanks for your update. It is working now.

You're welcome! Good news!

> There is one more issue we are seeing which is under the "Git" tab on kibana the private URL is displaying with username and key which will affect the

This is due to the fact that the username and password is set in the Git URLs of the projects.json (the URLs are directly mirrored to the dashboards. Please have a look at: https://help.github.com/en/articles/about-ssh, this should solve your problem. 

If this won't solve your problem, I can check how to modifiy the code (it shouldn't be difficult)

**Comment by asharabu** [comment]
Hi,
If we use ssh authentication it will not help https://github.com/asharabu/Testgit123 that should be ssh URL git@github.com:asharabu/Testgit123.git . But if you use ssh URL the projects.json file will not read ssh URL. We suspect that there should be code changes on grimoirelab/full which should read the key from override.cfg.

**Comment by valeriocos** [comment]
I'll have a look and go back to you in the next days, thanks

**Comment by valeriocos** [comment]
Hi @asharabu, a PR is available at: https://github.com/chaoss/grimoirelab-elk/pull/682
