### ISSUE TITLE
Dockerfile-full does not compile

### ISSUE THREAD

**Issue by florentk** [chaoss/grimoirelab#261]
after commit 1a1d4012425712b3bc2c9fd0a4c6c6bdf3cae550 Dockerfile-full does not build, I got this error :
```
kibiter-6.1.4-4-linux-x86_64/src/utils/streams/reduce_stream.js:40
    async transform(chunk, enc, callback) {
          ^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/kibiter-6.1.4-4-linux-x86_64/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```
When I try to install Kibiter on my local host with the last release (community-v6.1.4-4) I got the same error !

**Comment by jamesiri** [comment]
This is still an issue with the most current version of this package. I was able to get around it by adjusting the Dockerfile-full environment variable `ENV KB_VERSION=6.1.4-4` to `ENV KB_VERSION=6.1.4-1`.

**Comment by valeriocos** [comment]
Thank you @jamesiri for the feedback (cc @jgbarah)

**Comment by sduenas** [comment]
This is an old bug. The current version works.
