### ISSUE TITLE
pip3 install -e grimoirelab-perceval fails 'pip is not installed'

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab#316]
This worked just about 2 weeks ago, now it no longer works.
I'm trying to build a docker image of `grimoirelab` tools.
pip *is* installed (it worked 2 weeks ago), see Dockerfile for reference:
```
FROM debian:stretch-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        bash locales \
        gcc \
        git git-core \
        jq procps \
        python3 \
        python3-pip \
        python3-setuptools \
        python3-wheel \
        python3-venv \
        python3-dev \
        python3-gdbm \
        mariadb-client \
        vim unzip curl wget openssh-client \
        && \
    apt-get clean && \
    find /var/lib/apt/lists -type f -delete
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
ENV REPOS_DIR=/repos
ADD repos ${REPOS_DIR}
ADD provision-minimal /provision
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV LANG C.UTF-8
RUN provision/provision.sh
```
`provision/provision.sh` script is as follows:
```
#!/bin/bash
set -eo pipefail
repos=(grimoirelab-perceval grimoirelab-elk grimoirelab-sortinghat grimoirelab-kingarthur)
for r in "${repos[@]}"; do
  echo "INSTALLING ${r}"
  pip3 install -e "${REPOS_DIR}/$r";
done
```
Here is the docker output:
```
INSTALLING grimoirelab-perceval
Obtaining file:///repos/grimoirelab-perceval
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        code = compile(script, filename, 'exec')
      File "/tmp/easy_install-zkiaql1f/pandoc-2.0a4/setup.py", line 11
        error = f"pip is not installed, refer to <{url}> for instructions."
                                                                          ^
    SyntaxError: invalid syntax
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/repos/grimoirelab-perceval/setup.py", line 113, in <module>
        zip_safe=False)
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 699, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 725, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 906, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1145, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1131, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 258, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        code = compile(script, filename, 'exec')
      File "/tmp/easy_install-zkiaql1f/pandoc-2.0a4/setup.py", line 11
        error = f"pip is not installed, refer to <{url}> for instructions."
                                                                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /repos/grimoirelab-perceval/
The command '/bin/sh -c provision/provision.sh' returned a non-zero code: 1
```

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki , the problem should be due to setuptools/pip. We found the same problem with the Travis tests: https://github.com/chaoss/grimoirelab-perceval/pull/643/files

**Comment by lukaszgryglicki** [comment]
OK, please ping me when this is solved, thanks!

**Comment by valeriocos** [comment]
If I understand correctly, the fix should be done on your side. Try with the following changes

```
#!/bin/bash
set -eo pipefail
pip3 install --upgrade setuptools <--
pip3 install --upgrade pip            <--
repos=(grimoirelab-perceval grimoirelab-elk grimoirelab-sortinghat grimoirelab-kingarthur)
for r in "${repos[@]}"; do
  echo "INSTALLING ${r}"
  pip3 install -e "${REPOS_DIR}/$r";
done
```

**Comment by lukaszgryglicki** [comment]
Ohhh, ok, I'll try and let you know!

**Comment by lukaszgryglicki** [comment]
Worked OK, thanks for the quick reply!

**Comment by valeriocos** [comment]
You're welcome @lukaszgryglicki !
