### ISSUE TITLE
compose_elasticsearch extied(137) 

### ISSUE THREAD

**Issue by Alanscut** [chaoss/grimoirelab#367]
Hi all, I run this project with docker-compose,  as described in the README:

env:
```
Mac OS 10.15.5  8G

$ git --version
git version 2.19.1
$ docker --version
Docker version 19.03.12, build 48a66213fe
$ docker-compose --version
docker-compose version 1.26.2, build eefe0d31

$ cd grimoirelab/docker-compose

$ docker-compose up -d
```

then all the docker images are pulled successfully:
```
Creating docker-compose_mariadb_1       ... done
Creating docker-compose_elasticsearch_1 ... done
Creating docker-compose_hatstall_1      ... done
Creating docker-compose_kibiter_1       ... done
Creating docker-compose_mordred_1       ... done
```

When I visit `localhost:5601`, the browser shows: `Kibana server is not ready yet`
and about 5 minutes later, I check the docker status, the `compose_elasticsearch` has exited. Even if I rerun the command, it still exits after a few minutes. Did I do something wrong?
```
$ docker ps -a
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                        PORTS                    NAMES
845cf5492c97        bitergia/kibiter:community-v6.8.6-3                       "/docker_entrypoint.…"   25 minutes ago      Up 21 minutes                 0.0.0.0:5601->5601/tcp   docker-compose_kibiter_1
a28a65936b37        bitergia/mordred:latest                                   "/bin/sh -c ${DEPLOY…"   25 minutes ago      Up 25 minutes (healthy)                                docker-compose_mordred_1
8f1b7caff819        grimoirelab/hatstall:latest                               "/bin/sh -c ${DEPLOY…"   25 minutes ago      Up 25 minutes                 0.0.0.0:8000->80/tcp     docker-compose_hatstall_1
a9b2ca9d4be6        mariadb:10.0                                              "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes                 3306/tcp                 docker-compose_mariadb_1
1324b075b0cf        docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6   "/usr/local/bin/dock…"   25 minutes ago      Exited (137) 12 minutes ago                            docker-compose_elasticsearch_1
```

**Comment by zhquan** [comment]
Hi @Alanscut,

Could you share the elasticsearch container error?

Check if your error is
```
elasticsearch_1  | ERROR: bootstrap checks failed
elasticsearch_1  | max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```
If so, try solving it with https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144

Best,
Quan

**Comment by vchrombie** [comment]
Hi @Alanscut 
Thanks for raising the issue and sorry for the inconvenience caused.
Let me see if I can help you.

> When I visit `localhost:5601`, the browser shows: `Kibana server is not ready yet`

I have experienced this once, this usually happens if you have another kibana instance running. 
Can you try checking the indices 
```
curl -XGET -k "https://admin:admin@localhost:9200/_cat/indices?v"
```

If you see multiple kibana instances, like kibana_1, kibana_2 then it should be the problem. You can resolve it by deleting the additional indices.

Coming to the problem with elasticsearch, I would support @zhquan's comment.

You can check this for more information.
https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#low-virtual-memory-

**Comment by Alanscut** [comment]
@zhquan @vchrombie thanks! After setting `vm.max_map_count=262144`, it works well

**Comment by Alanscut** [comment]
hi all, now I can visit localhost:5601, but the result is empty, I don't konw if I should modify the `ELASTICSEARCH_URL` to `http:(IP of my server):9200` in `docker-compose.yml` and `docker-compose-secure.yml`. I'm a new to docker, please forgive my ignorance 😢 
![image](https://user-images.githubusercontent.com/14244944/89013462-8160d600-d346-11ea-9347-6cbf6f0879a8.png)

when I check the log `mordred`, there is an Error:
```
grimoire_elk.elk - ERROR - Error feeding raw from git (https://github.com/chaoss/grimoirelab.git): git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/https://github.com/chaoss/grimoirelab.git-git'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 162, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 228, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 161, in fetch_items
    latest_items, no_update)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 274, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 325, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 833, in clone
    cls._exec(cmd, env=env)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 1338, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/https://github.com/chaoss/grimoirelab.git-git'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

2020-07-31 07:45:03,431 - grimoire_elk.elk - ERROR - [git] Problem executing study enrich_areas_of_code:git, RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
2020-07-31 07:45:03,431 - sirmordred.task_manager - ERROR - [git] Exception in Task Manager RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_manager.py", line 97, in run
    task.execute()
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_enrich.py", line 436, in execute
    raise e
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_enrich.py", line 426, in execute
    self.__studies(retention_time)
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_enrich.py", line 339, in __studies
    do_studies(ocean_backend, enrich_backend, studies_args, retention_time=retention_time)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 392, in do_studies
    raise e
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 389, in do_studies
    study(ocean_backend, enrich_backend, **params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/git.py", line 576, in enrich_areas_of_code
    areas_of_code(git_enrich=enrich_backend, in_conn=in_conn, out_conn=out_conn)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/study_ceres_aoc.py", line 230, in areas_of_code
    ndocs = aoc.analyze()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/ceres_base.py", line 96, in analyze
    for item_block in self._in.read_block(size=self._block_size, from_date=from_date):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/study_ceres_aoc.py", line 99, in read_block
    preserve_order=True):
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/helpers/__init__.py", line 364, in scan
    request_timeout=request_timeout, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
```

**Comment by Alanscut** [comment]
> If you see multiple kibana instances, like kibana_1, kibana_2 then it should be the problem. You can resolve it by deleting the additional indices.
@vchrombie BTW, I remove the extra indices, and just leave one, but when i restart the docker, it will appear again, but it seems that no impact for me.

**Comment by Alanscut** [comment]
**log of elasticsearch**
```
[2020-07-31T08:36:54,272][INFO ][o.e.n.Node               ] [BLL8mVs] starting ...
[2020-07-31T08:36:54,429][INFO ][o.e.t.TransportService   ] [BLL8mVs] publish_address {172.18.0.3:9300}, bound_addresses {0.0.0.0:9300}
[2020-07-31T08:36:54,487][INFO ][o.e.b.BootstrapChecks    ] [BLL8mVs] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2020-07-31T08:36:57,563][INFO ][o.e.c.s.MasterService    ] [BLL8mVs] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {BLL8mVs}{BLL8mVs3RCqWyYXMo1j61w}{FIAJ4tgDRgayHClvMJ5YOg}{172.18.0.3}{172.18.0.3:9300}
[2020-07-31T08:36:57,578][INFO ][o.e.c.s.ClusterApplierService] [BLL8mVs] new_master {BLL8mVs}{BLL8mVs3RCqWyYXMo1j61w}{FIAJ4tgDRgayHClvMJ5YOg}{172.18.0.3}{172.18.0.3:9300}, reason: apply cluster state (from master [master {BLL8mVs}{BLL8mVs3RCqWyYXMo1j61w}{FIAJ4tgDRgayHClvMJ5YOg}{172.18.0.3}{172.18.0.3:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
[2020-07-31T08:36:57,663][INFO ][o.e.h.n.Netty4HttpServerTransport] [BLL8mVs] publish_address {172.18.0.3:9200}, bound_addresses {0.0.0.0:9200}
[2020-07-31T08:36:57,663][INFO ][o.e.n.Node               ] [BLL8mVs] started
[2020-07-31T08:36:58,475][INFO ][o.e.g.GatewayService     ] [BLL8mVs] recovered [6] indices into cluster_state
[2020-07-31T08:36:58,494][WARN ][o.e.g.G.InternalPrimaryShardAllocator] [BLL8mVs] [git-aoc_demo_enriched][1]: failed to list shard for shard_started on node [BLL8mVs3RCqWyYXMo1j61w]
org.elasticsearch.action.FailedNodeException: Failed node [BLL8mVs3RCqWyYXMo1j61w]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:236) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$200(TransportNodesAction.java:151) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:210) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1114) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1226) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1200) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:703) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:736) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-6.8.6.jar:6.8.6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [BLL8mVs][172.18.0.3:9300][internal:gateway/local/started_shards[n]]
Caused by: org.elasticsearch.ElasticsearchException: failed to load started shards
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:169) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:138) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:259) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:255) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:692) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.6.jar:6.8.6]
        ... 3 more
Caused by: org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:8, file:/usr/share/elasticsearch/data/nodes/0/indices/cZQofRWIRRezUNHTKtrMkw/_state/state-8.st]
        at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:165) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:306) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:324) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:138) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:259) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:255) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:692) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.6.jar:6.8.6]
        ... 3 more
Caused by: java.io.IOException: failed to read [id:8, file:/usr/share/elasticsearch/data/nodes/0/indices/cZQofRWIRRezUNHTKtrMkw/_state/state-8.st]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:300) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:324) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:138) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:259) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:255) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:692) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.6.jar:6.8.6]
        ... 3 more
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/nodes/0/indices/cZQofRWIRRezUNHTKtrMkw/_state/state-8.st
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:374) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:425) ~[?:?]
        at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77) ~[lucene-core-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:30:25]
        at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:183) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:296) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:324) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:138) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:259) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:255) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:692) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.6.jar:6.8.6]
        ... 3 more
[2020-07-31T08:36:59,877][INFO ][o.e.c.r.a.AllocationService] [BLL8mVs] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.grimoirelab-sigils][3], [.kibana_1][0]] ...]).
[2020-07-31T08:37:00,088][INFO ][o.e.c.m.MetaDataCreateIndexService] [BLL8mVs] [.kibana_3] creating index, cause [api], templates [], shards [1]/[1], mappings [doc]
[2020-07-31T08:37:00,095][INFO ][o.e.c.r.a.AllocationService] [BLL8mVs] updating number_of_replicas to [0] for indices [.kibana_3]
[2020-07-31T08:37:00,389][WARN ][o.e.d.r.a.a.i.RestGetIndicesAction] [BLL8mVs] [types removal] The parameter include_type_name should be explicitly specified in get indices requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions.
[2020-07-31T08:37:00,399][INFO ][o.e.c.m.MetaDataMappingService] [BLL8mVs] [.kibana_3/Pl3z23FES_Cm-J9O1E5FDQ] update_mapping [doc]
[2020-07-31T08:37:00,690][INFO ][o.e.c.m.MetaDataMappingService] [BLL8mVs] [.kibana_3/Pl3z23FES_Cm-J9O1E5FDQ] update_mapping [doc]
[2020-07-31T08:37:30,462][INFO ][o.e.c.m.MetaDataIndexTemplateService] [BLL8mVs] adding template [kibana_index_template:.kibana] for index patterns [.kibana]
[2020-07-31T08:37:31,250][INFO ][o.e.c.m.MetaDataIndexTemplateService] [BLL8mVs] adding template [kibana_index_template:.kibana] for index patterns [.kibana]
[2020-07-31T08:37:34,415][WARN ][o.e.d.r.a.a.i.RestPutMappingAction] [BLL8mVs] [types removal] Specifying types in put mapping requests is deprecated. To be compatible with 7.0, the mapping definition should not be nested under the type name, and the parameter include_type_name must be provided and set to false.
[2020-07-31T08:37:34,422][INFO ][o.e.c.m.MetaDataMappingService] [BLL8mVs] [.kibana_3/Pl3z23FES_Cm-J9O1E5FDQ] update_mapping [doc]
```

**Comment by zhquan** [comment]
Hi @Alanscut,

If you have different questions it would be better if you open a new one. This way it will be easier for the rest of the community for future reference just in case anyone is having the same problem.

If this issue is solved, close this one and open a new one, thanks.

Best,
Quan

**Comment by Alanscut** [comment]
ok, i will close this and open an new issue
