### ISSUE TITLE
update projects.json in local, then restart `mordred` container, but dashboard still shows old projects

### ISSUE THREAD

**Issue by Alanscut** [chaoss/grimoirelab#370]
Hi, 

I run this project with `docker-compose`, and it works well. then I want to update the `projects.json`, add some new projects and remove some old projects. To update projects.json in mordred container, I restart mordred with `docker restart docker-compose_mordred_1`, then the projects.json in container is updated, but the dashboard still shows the old project.

logs of modred:
```
Collection for git: starting...
Domain 2n.cz added to organization 2N Telekomunikace
....
Domain xorcom.com added to organization Xorcom
2020-08-12 02:05:05,039 - grimoire_elk.elk - ERROR - Error feeding raw from git (): git command - fatal: repository '' does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 162, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 228, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 161, in fetch_items
    latest_items, no_update)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 274, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 325, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 833, in clone
    cls._exec(cmd, env=env)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 1338, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: repository '' does not exist

Warning: Domain '2n.cz' already exists in the registry. Not updated.
...
Warning: Domain 'epfl.ch' already exists in the registry. Not updated.
2020-08-12 02:15:14,364 - grimoire_elk.elk - ERROR - Error feeding raw from git (https://github.com/apache/hadoop): <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1285, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1145, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1190, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1141, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 945, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 888, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1291, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 860, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 162, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 228, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 161, in fetch_items
    latest_items, no_update)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 279, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 316, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 937, in sync
    pack_name, refs = self._fetch_pack()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 1115, in _fetch_pack
    fd.write)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1398, in fetch_pack
    b"git-upload-pack", url)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1282, in _discover_references
    resp, read = self._http_request(url, headers, allow_compression=True)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1261, in _http_request
    resp = self.opener.open(req)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1328, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1287, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
Warning: multiple top domains for snoopy.citi.umich.edu sub-domain. Domain citi.umich.edu selected.
Warning: multiple top domains for snoopy.citi.umich.edu sub-domain. Domain citi.umich.edu selected.
...
```

**original projects.json:**
```
{
    "grimoirelab": {
      "git": ["https://github.com/DaveGamble/cJSON"]
    },
    "linux": {
      "git":[ "https://github.com/torvalds/linux" ]
    },
    "tensorflow": {
      "git":[ "https://github.com/tensorflow/tensorflow" ]
    },
    "hadoop": {
      "git":[ "https://github.com/apache/hadoop" ]
    }
}
```
**updated projects.json**
removed `grimoirelab`, and add some new projects
```
{
    "linux": {
      "git":[ "https://github.com/torvalds/linux" ]
    },
    "tensorflow": {
      "git":[ "https://github.com/tensorflow/tensorflow" ]
    },
    "hadoop": {
      "git":[ "https://github.com/apache/hadoop" ]
    },
   "xxx": {
      "git":[ "https://github.com/xxx/xxx" ]
    },
    ...
}
```

**Comment by Alanscut** [comment]
The error message doesn't seem to have much impact, and a few hours later the newly added project data was presented in the dashboard. 
Expecting your guidance.

**Comment by zhquan** [comment]
Hi @Alanscut,

> I run this project with docker-compose, and it works well. then I want to update the projects.json, add some new projects and remove some old projects. To update projects.json in mordred container, I restart mordred with docker restart docker-compose_mordred_1, then the projects.json in container is updated, but the dashboard still shows the old project.

Make sure the enrichment phase is finished or you cannot see the new repositories on the dashboard.
```
[git] collection phase starts
...
...
[git] collection phase finished in xx:xx:xx
...
...
[git] enrichment phase starts
...
...
[git] enrichment phase finished in xx:xx:xx
```
You don't need to restart the Mordred container if you change the projects.json it will apply automatically on the next execution. But if you want to start collecting the new repositories at the moment that you update the projects.json you can restart it.

> 2020-08-12 02:05:05,039 - grimoire_elk.elk - ERROR - Error feeding raw from git (): git command - fatal: repository '' does not exist

This error seems you added an empty repository at projects.json on the section `git`

> 2020-08-12 02:15:14,364 - grimoire_elk.elk - ERROR - Error feeding raw from git (https://github.com/apache/hadoop): <urlopen error [Errno 110] Connection timed out>

At some point, the connection was closed. But on the next execution, it will try again.

> The error message doesn't seem to have much impact, and a few hours later the newly added project data was presented in the dashboard.

When the error is raised with one repository Mordred will go to the next one. When the enrichment phase is finished you will see the new repositories on the dashboard.

This is the expected behavior.

I hope it helps you.

Best,
Quan

**Comment by Alanscut** [comment]
hI @zhquan ,

Thank you very much for your detailed explanation, which helps me a lot. Having check the projects.josn, I found one of a project's git is `[""]`, now I figured the error messages out.

Best,
Alan
