### ISSUE TITLE
Git data is not being collected due to 'could not read Username'

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab#40]
Using the latest version provided by our Dev team, I'm not able to collect data for the YoctoProject.

How to reproduce:
- use the versions below
- use a password protected like https://github.com/patternfly/patternfly-planning.git

The data collection is stuck, not sure whether the thread is alive or waiting for a password.

```
2017-11-22 10:32:45,677 - grimoire_elk.arthur - ERROR - Error feeding ocean from git (https://github.com/patternfly/patternfly-planning.git): git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/https://github.com/patternfly/patternfly-planning.git-git'...
fatal: could not read Username for 'https://github.com': No such device or address

Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 116, in feed_backend
    ocean_backend.feed(latest_items=latest_items)
  File "./grimoire_elk/ocean/elastic.py", line 204, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 120, in fetch
    latest_items)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 141, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 186, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 763, in clone
    cls._exec(cmd, env=env)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 1220, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/https://github.com/patternfly/patternfly-planning.git-git'...
fatal: could not read Username for 'https://github.com': No such device or address
```

This error was found with the version:

```
SORTINGHAT='641dabd71d4f4a23547592a10096240343268bd1'      
GRIMOIREELK='9a69a31a6499402cddb3c622f12dc5d11e490fed'     
PERCEVAL='fcae408a56f16a25f1f62abc6c01b61d2e0dc100'        
KIBITER='f7bf173cb1d79418b9909d877adfb998ce7b52da'         
GRIMOIRELAB_GITHUB_IO='2f71c036020f6873efdd079f4ec2b5f26584cb2b'                                                       
ARTHUR='3efff3311b52222b7d06bf63ce97f8a42572bc06'          
USE_CASES='31ea49ecc28f3e27aa29fddb0e01b7f475069b6a'       
PANELS='ffe73323afe84e491d0b1705e86a7db3588bff38'          
MORDRED='024019f5ee1df7096f91f7b41286cd58e55e6495'         
TRAINING='9df30c3ec955387a423f261bb141f74133bf7ff7'        
PERCEVAL_MOZILLA='423615b9745ab0b0e577701504e46e0f32aab6a3'                                                            
PERCEVAL_PUPPET='9c0d4c72a0e9b3c7c1e3295f72ebe70c5c874084' 
REPORTS='4ad4f7c9d8cd5eb728a95c3a358d8aa339102c75'         
GRIMOIRELAB_TOOLKIT='95d271af32744eb38f73df592f2e0dc5ea97683b'                                                         
PERCEVAL_OPNFV='0bec845df7e17965892dfb1181da0ab1c77168dc'  
GRIMOIRELAB='efd656ff641623e6a639e095f14f38a71cacc094' 
```

**Comment by sduenas** [comment]
That repository doesn't exist. Closing this ticket because it isn't a bug.

**Comment by sduenas** [comment]
@sanacl does that repository exist? GitHub returns a 404 error.

**Comment by sduenas** [comment]
It's not been reported again. Closing it.
