### ISSUE TITLE
Because the server could not access, a route was deleted, and now there is no content on the page

### ISSUE THREAD

**Issue by No6-start** [chaoss/grimoirelab#422]
Why can't I upload the gitlab attachment, I posted my error log?

**Comment by No6-start** [comment]
2021-04-09 09:00:12,201 - grimoire_elk.enriched.git - INFO - [git] study areas_of_code Processing repo: http://git.1an.com/front/owss.git
2021-04-09 09:00:12,211 - grimoire_elk.enriched.ceres_base - INFO - [git] study areas_of_code reading items since the beginning of times
2021-04-09 09:00:12,214 - elasticsearch - WARNING - GET http://elasticsearch:9200/git_demo_raw/_search?scroll=300m&size=500 [status:400 request:0.003s]
2021-04-09 09:00:12,214 - grimoire_elk.elk - ERROR - [git] Problem executing study enrich_areas_of_code:git, RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
2021-04-09 09:00:12,214 - sirmordred.task_manager - ERROR - [git] Exception in Task Manager RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_manager.py", line 97, in run
    task.execute()
  File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_enrich.py", line 436, in execute
    raise e
  File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_enrich.py", line 426, in execute
    self.__studies(retention_time)
  File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_enrich.py", line 339, in __studies
    do_studies(ocean_backend, enrich_backend, studies_args, retention_time=retention_time)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/elk.py", line 392, in do_studies
    raise e
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/elk.py", line 389, in do_studies
    study(ocean_backend, enrich_backend, **params)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/enriched/git.py", line 576, in enrich_areas_of_code
    areas_of_code(git_enrich=enrich_backend, in_conn=in_conn, out_conn=out_conn)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/enriched/study_ceres_aoc.py", line 230, in areas_of_code
    ndocs = aoc.analyze()
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/enriched/ceres_base.py", line 96, in analyze
    for item_block in self._in.read_block(size=self._block_size, from_date=from_date):
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/enriched/study_ceres_aoc.py", line 99, in read_block
    preserve_order=True):
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/helpers/__init__.py", line 364, in scan
    request_timeout=request_timeout, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
2021-04-09 09:00:29,621 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1c4c360320>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /api/v4/projects/core%2Fexweb

**Comment by zhquan** [comment]
Hi @No6-start 

```
2021-04-09 09:00:12,214 - grimoire_elk.elk - ERROR - [git] Problem executing study enrich_areas_of_code:git, RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
2021-04-09 09:00:12,214 - sirmordred.task_manager - ERROR - [git] Exception in Task Manager RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
```
When you execute the first time the git study `enrich_areas_of_code` the index is empty and it does not contain any mapping. You can execute again or just wait for the next execution and you will not see this error. Any way this error does not affect `gitlab`

```
2021-04-09 09:00:29,621 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1c4c360320>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /api/v4/projects/core%2Fexweb
```
This is a warning, but make sure that your token can access the repo `http:xxx/core/exweb`

> Why can't I upload the gitlab attachment, I posted my error log?

Search for `gitlab:merge` on your logs and check if there are any errors related to it. If you cannot see the message `[gitlab:merge] enrichment finished` you will not see data on your dashboard.

Check your `gitlab` indexes.
1. On your dashboard go to `Dev tools`
2. Execute `GET _cat/indices`
3. Check if your `gitlab-merge` indexes have any items



The next time it would be great if you use the `code format` for the log/code message. Paste the log/code, select the log/code, and click on `<>`

I hope it helps you.

Best,
Quan

**Comment by No6-start** [comment]
I rebooted my server, and I rebooted my grimoirelab. After a few minutes, the log did not refresh
[Uploading all.log…]()

**Comment by zhquan** [comment]
Hi @No6-start 

```
2021-04-12 02:47:09,755 - sirmordred.task_manager - ERROR - [Global tasks] Exception in Task Manager Expecting value: line 8 column 9 (char 181)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_manager.py", line 97, in run
    task.execute()
  File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_projects.py", line 133, in execute
    projects = json.load(fprojects)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 9 (char 181)
2021-04-12 02:47:09,756 - sirmordred.sirmordred - ERROR - <class 'json.decoder.JSONDecodeError'>
```
Your `projects.json` is not valid. You can validate it via online as https://jsoneditoronline.org/ 

Best,
Quan

**Comment by No6-start** [comment]
[all.log](https://github.com/chaoss/grimoirelab/files/6295000/all.log)
There's still nothing on the page

**Comment by zhquan** [comment]
@No6-start 
### GITLAB
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='git.1an.com', port=80): Max retries exceeded with url: /api/v4/projects/midl%2Fdysub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5c60b9b38>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
Your server (git.1an.com) close the connection.

Anyway, check with [Perceval](https://github.com/chaoss/grimoirelab-perceval) if your TOKEN is correct
```
perceval --enterprise-url http://git.1an.com core nclm -t TOKEN
```
You can run it on the `mordred` container. To enter into the container run the next command.
```
docker exec -it MORDRED_CONTAINER_NAME /bin/bash
```
### GIT
```
2021-04-12 08:12:36,483 - grimoire_elk.elk - ERROR - Error feeding raw from git (http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@git.1an.com/midl/dysub.git): git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@git.1an.com/midl/dysub.git-git'...
fatal: unable to access 'http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@git.1an.com/midl/dysub.git/': Could not resolve host: git.1an.com
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/elk.py", line 162, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 228, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
    for item in items:
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/git.py", line 161, in fetch_items
    latest_items, no_update)
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/git.py", line 274, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/git.py", line 325, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/git.py", line 833, in clone
    cls._exec(cmd, env=env)
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/git.py", line 1338, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@git.1an.com/midl/dysub.git-git'...
fatal: unable to access 'http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@git.1an.com/midl/dysub.git/': Could not resolve host: git.1an.com

```
It seems that your credentials is not working or the repo does not exist.
Try to clone the repo
```
git clone http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@git.1an.com/midl/dysub.git/
```
And try to execute with Perceval
```
perceval git http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@git.1an.com/midl/dysub.git/
```

**Comment by No6-start** [comment]
I found that only part of the data is displayed in merge. I should have thousands of merges, but the number displayed is very small.

**Comment by zhquan** [comment]
@No6-start - have a look your logs if you see any error related to `gitlab:merge`. And make sure that the alias is pointing the correct enriched index `GET _cat/aliases`

**Comment by No6-start** [comment]
I found that the GIT and merge data displayed on the page are not the whole content. What is the reason for this

**Comment by No6-start** [comment]
Am I using the right configuration?
`[gitlab:merge]
category = merge_request
api-token = phU-DaG9zSKGTvsz5BH4
enterprise-url = http://xxx
raw_index = gitlab_merges_demo_raw
enriched_index = gitlab_merges_demo_enriched
no-archive = true
sleep-for-rate = true
`

**Comment by zhquan** [comment]
@No6-start - yes the configuration is correct.

> I don't understand enriched_ index raw_ What does index mean

Well, a nutshell is when Mordred fetches the items it will store in the `raw_index` and when Mordred processes those items it will store in the `enriched_index`. Then the dashboard will show the content of the enriched indexes.

> I found that the GIT and merge data displayed on the page are not the whole content

The time picker is `Lasts 5 years`? and have a look if you add some filters on the dashboards

**Comment by No6-start** [comment]
Page selection was five years ago, but there are 8K merges in gitlab and only 800 on the page. Why

**Comment by zhquan** [comment]
@No6-start - I cannot help you if I don't have logs, indexes, or any other information.

You can check these:
- if the merges in your dashboard are the newest or the oldest.
- If there are any errors in your logs.
- If you are missing the merges from `http://git.1an.com/midl/dysub` or `http://git.1an.com/core/nclm`.

**Comment by No6-start** [comment]
The page shows that there are some merging records every month, but when it is adjusted to 30 days, only some are displayed, but my gitlab has merging records every day. The log is the content after the application is started until the merge record is generated.
[all.log](https://github.com/chaoss/grimoirelab/files/6309162/all.log)

**Comment by zhquan** [comment]
@No6-start 

You have a lot of connection errors. Each time you receive this error, the collection phase for that repository will stop and continue to the next one. Your server closes the connection when Mordred makes queries to get the merge info. I do not know the limit of the requests of your server.

```
2021-04-14 08:03:19,728 - grimoire_elk.elk - ERROR - Error feeding raw from gitlab (http://192.168.144.93/core/nbz): HTTPConnectionPool(host='git.1an.com', port=80): Max retries exceeded with url: /api/v4
....
....
requests.exceptions.ConnectionError: HTTPConnectionPool(host='git.1an.com', port=80): Max retries exceeded with url: /api/v4/projects/core%2Fnbz/merge_requests?id=core%2Fnbz&order_by=updated_at&page=2&per_page=100&sort=asc&state=all&updated_after=1970-01-01T00%3A00%3A00%2B00%3A00&view=simple&state=all&order_by=updated_at&sort=asc&view=simple&per_page=100&updated_after=1970-01-01T00%3A00%3A00%2B00%3A00 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff3483ab8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
Anyway if you let Mordred still executing it will fetch all of them, due to Mordred fetch items incrementally.
```
2021-04-14 08:00:46,594 - grimoire_elk.raw.elastic - INFO - [gitlab] Incremental from: 2020-07-17 02:03:19+00:00 for http://192.168.144.93/core/eclmweb
2021-04-14 08:00:47,327 - grimoire_elk.raw.elastic - INFO - [gitlab] Incremental from: 2021-02-24 01:01:34+00:00 for http://192.168.144.93/core/epolicy
2021-04-14 08:00:48,590 - grimoire_elk.raw.elastic - INFO - [gitlab] Incremental from: 2020-06-10 09:52:13+00:00 for http://192.168.144.93/core/its 
```

**Comment by No6-start** [comment]
How should I adjust

**Comment by zhquan** [comment]
@No6-start - You can let Mordred keep running and it will fetch them all (I don't know how long it will take). Or increase the request limit on your server.

**Comment by No6-start** [comment]
How can I increase the maximum number of requests on the server？

**Comment by zhquan** [comment]
@No6-start - your GitLab server
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='git.1an.com', port=80): Max retries exceeded
```

**Comment by No6-start** [comment]
How can I handle this exception? Can I ask the app to only get this year's records

**Comment by zhquan** [comment]
@No6-start 

> How can I handle this exception? Can I ask the app to only get this year's records

Yes, add the parameter `from-date = 2021-01-01` to `gitlab:merge` on your `setup.cfg`.
```
[gitlab:merge]
raw_index = ...
enriched_index = ...
...
from-date = 2021-01-01
```

**Comment by No6-start** [comment]
Is it possible to reduce the pressure by changing the time to this year

**Comment by zhquan** [comment]
> Is it possible to reduce the pressure by changing the time to this year

Well, it depends on how many merges you have since 2021-01-01, but yes for sure.

**Comment by zhquan** [comment]
@No6-start - Can we close the issue?

**Comment by No6-start** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Quan ***@***.***&gt;; 
发送时间: 2021年4月27日(星期二) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chaoss/grimoirelab] Because the server could not access, a route was deleted, and now there is no content on the page (#422)





 
@No6-start - Can we close the issue?
 
&mdash;
