### ISSUE TITLE
logger.info(f"Pulling Askbot data from {from_date}") - ^ SyntaxError: invalid syntax Failed to start SirMordred: 1

### ISSUE THREAD

**Issue by mneedham** [chaoss/grimoirelab#440]
Hi,

I've been trying to build a Docker image for version [0.2.56](https://github.com/chaoss/grimoirelab/blob/master/releases/0.2.56), following the instructions at https://github.com/chaoss/grimoirelab/blob/master/BUILDING.md#producing-your-own-grimoirelab-docker-containers, but am running into the following error:

```
docker run -p 127.0.0.1:5601:5601  \
-v $(pwd)/default-grimoirelab-settings/projects.json:/projects.json \
-v $(pwd)/default-grimoirelab-settings/setup.cfg:/setup.cfg \
-t grimoirelab/full
```

Output

```
Starting container: 33dbce5b5f90
Starting Elasticsearch
[ ok ] Starting Elasticsearch Server:.
Waiting for Elasticsearch to start...
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      -                   
Elasticsearch started
Starting MariaDB
[ ok ] Starting MariaDB database server: mysqld ..
Waiting for MariaDB to start...
tcp6       0      0 :::3306                 :::*                    LISTEN      -                   
MariaDB started
Starting Kibiter
Waiting for Kibiter to start...
...Kibiter started
Starting SirMordred to build a GrimoireLab dashboard
Python 3.5.3
This will usually take a while...
Traceback (most recent call last):
  File "/usr/local/bin/sirmordred", line 39, in <module>
    from sirmordred.config import Config
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/config.py", line 29, in <module>
    from sirmordred.task import Task
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/task.py", line 28, in <module>
    from grimoire_elk.elk import get_ocean_backend
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 35, in <module>
    from .utils import get_connectors, get_connector_from_name, get_elastic
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/utils.py", line 38, in <module>
    from perceval.backends.core.askbot import Askbot, AskbotCommand
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/askbot.py", line 89
    logger.info(f"Pulling Askbot data from {from_date}")
                                                      ^
SyntaxError: invalid syntax
Failed to start SirMordred: 1
```

This error reads to me like Python 2 is trying to process a Python 3 f-string, but I've tried explicitly removing Python 2 from the Docker image and I still get the error. Also the `/usr/local/bin/sirmordred` script explicitly uses Python 3 anyway, so I don't see how it'd be possible.

Any ideas?

Cheers, Mark

**Comment by zhquan** [comment]
Hi @mneedham 

The `f-string` is available since `Python 3.6` and I see that you are using `Python 3.5.3` please try again using `Python 3.6` or newer.

I hope it helps you.

Best,
Quan

**Comment by mneedham** [comment]
@zhquan oh cool, didn't know that. How do I get a newer version of Python onto the Docker image - from what I can tell it's being installed via apt-get, so wouldn't it be picking up the latest version of Python 3? 

https://github.com/chaoss/grimoirelab/blob/master/docker/Dockerfile-installed#L25

**Comment by zhquan** [comment]
@mneedham - sorry for the late reply could you try this https://github.com/chaoss/grimoirelab/issues/373#issuecomment-712146010?

**Comment by mneedham** [comment]
@zhquan cool thanks, yeh that works. I'm still stuck on an issue with GitHub authorisation, which is what led me to attempting to build the image myself. I've tried refreshing my GitHub personal token a few times, but I always get the following error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grimoire_elk/elk.py", line 162, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.6/site-packages/grimoire_elk/raw/elastic.py", line 228, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.6/site-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
    for item in items:
  File "/usr/local/lib/python3.6/site-packages/perceval/backend.py", line 224, in fetch
    self.client = self._init_client()
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 304, in _init_client
    self.archive, from_archive, self.ssl_verify)
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 671, in __init__
    self._choose_best_api_token()
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 990, in _choose_best_api_token
    self._update_current_rate_limit()
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 1125, in _update_current_rate_limit
    self._update_access_token()
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 995, in _update_access_token
    jwt_token = self._create_jwt_token()
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 1019, in _create_jwt_token
    private_key = self._read_pem()
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 1028, in _read_pem
    with open(self.github_app_pk_filepath, 'r') as private_file:
TypeError: expected str, bytes or os.PathLike object, not NoneType
2021-07-28 12:49:49,372 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/finbourne/sample-notebooks): expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 1116, in _update_current_rate_limit
    response = super().fetch(url)
  File "/usr/local/lib/python3.6/site-packages/perceval/client.py", line 143, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, auth)
  File "/usr/local/lib/python3.6/site-packages/perceval/client.py", line 186, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.6/site-packages/perceval/client.py", line 181, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
```

**Comment by zhquan** [comment]
@mneedham you can add [sleep-for-rate = true](https://github.com/chaoss/grimoirelab-sirmordred#github-) (when the rate limit is reached Mordred will sleep until the rate limit is reset.) on the setup.cfg also  add more GitHub tokens to increase the rate limit as `api-token = [TOKEN-1, TOKEN-2, ...]`

**Comment by mneedham** [comment]
@zhquan I have that property set already:

```
[github]
api-token = xyz
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
```

**Comment by zhquan** [comment]
@mneedham - I have no issue fetching https://github.com/finbourne/sample-notebooks using mordred or perceval 

Could you try it with [perceval](https://github.com/chaoss/grimoirelab-perceval) if your token is correct? You can execute it in your Mordred container if you want.

`perceval finbourne sample-notebooks --sleep-for-rate -t TOKEN`


This https://github.com/chaoss/grimoirelab/issues/440#issuecomment-888313235 is your current setup.cfg? I see the error is related when you use `github-app-id` and `github-app-pk-filepath` instead of `api-token`.
```
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 995, in _update_access_token
    jwt_token = self._create_jwt_token()
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 1019, in _create_jwt_token
    private_key = self._read_pem()
  File "/usr/local/lib/python3.6/site-packages/perceval/backends/core/github.py", line 1028, in _read_pem
    with open(self.github_app_pk_filepath, 'r') as private_file:
TypeError: expected str, bytes or os.PathLike object, not NoneType
2021-07-28 12:49:49,372 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/finbourne/sample-notebooks): expected str, bytes or os.PathLike object, not NoneType
```

**Comment by mneedham** [comment]
@zhquan I don't seem to have an issue pulling down GitHub repositories - those work for me even without providing any GitHub credentials.

Yeh the code I pasted above is from my `setup.cfg`:


```
docker run -p 127.0.0.1:5601:5601  \       
-v $(pwd)/default-grimoirelab-settings/projects.json:/projects.json \
-v $(pwd)/default-grimoirelab-settings/setup.cfg:/setup.cfg -v $(pwd)/docker/mordred-infra.cfg:/infra.cfg -v $(pwd)/docker/mordred-project.cfg:/project.cfg -v $(pwd)/docker/logs:/logs \
--user root -it grimoirelab/full
```

**Comment by zhquan** [comment]
@mneedham Could you share your `setup.cfg` and `projects.json` to see if I can reproduce the error?

Why are you using three setup (setup.cfg, infra.cfg, and project.cfg)?

**Comment by mneedham** [comment]
At some point in time I was getting an exception that said I had incorrect config for Elasticsearch and sortinghat, so I started editing the various config files to see if I could get past those errors. 

Below are my config files:

setup.cfg
```
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

#[bugzillarest]
#raw_index = bugzillarest_demo_raw
#enriched_index = bugzillarest_demo_enriched
#no-archive = true

#[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
api-token = xyz
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched

#[gitlab:issues]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_issues_demo_raw
#enriched_index = gitlab_issues_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#sleep-for-rate = true

#[gitlab:merge]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_merges_demo_raw
#enriched_index = gitlab_merges_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#category = merge_request
#sleep-for-rate = true

#[jira]
#raw_index = jira_demo_raw
#enriched_index = jira_demo_enriched
#no-archive = true

#[pipermail]
#raw_index = pipermail_demo_raw
#enriched_index = pipermail_demo_enriched
#no-verify = true

#[mediawiki]
#raw_index = mediawiki_demo_raw
#enriched_index = mediawiki_demo_enriched
#no-archive = true

#[meetup]
#raw_index = meetup_demo_raw
#enriched_index = meetup_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = "300"

#[stackexchange]
#raw_index = stackexchange_demo_raw
#enriched_index = stackexchange_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[slack]
#raw_index = slack_demo_raw
#enriched_index = slack_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[supybot]
#raw_index = supybot_demo_raw
#enriched_index = supybot_demo_enriched

#[twitter]
#raw_index = twitter_demo_raw
#enriched_index = twitter_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = 300

## studies based on enriched indexes

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash
```

projects.json
```
{
    "finbourne": {
      "meta": {
        "title": "Finbourne"
      },
      "git": [
          "https://github.com/finbourne/lusid-sdk-python-preview.git",
          "https://github.com/finbourne/sample-notebooks.git",
          "https://github.com/finbourne/lusid-sdk-csharp.git",
          "https://github.com/finbourne/drive-sdk-python.git",
          "https://github.com/finbourne/lusid-sdk-generators.git"

        ],
        "github": [
          "https://github.com/finbourne/lusid-sdk-python-preview",
          "https://github.com/finbourne/sample-notebooks",
          "https://github.com/finbourne/lusid-sdk-csharp",
          "https://github.com/finbourne/drive-sdk-python",
          "https://github.com/finbourne/lusid-sdk-generators"

        ]
    }
  }
```

**Comment by zhquan** [comment]
@mneedham I can fetch all of them without issues with the correct token, but I can reproduce the error when I use an invalid token.

Your token is not a valid token. Make sure that your token has read permissions. And again use `perceval` to check if your token is valid.

Not valid token:
```
$ perceval github finbourne lusid-sdk-csharp -t xyz                                                                                                                                                            
[2021-07-29 12:17:12,044] - Sir Perceval is on his quest.
[2021-07-29 12:17:12,362] - Error!: expected str, bytes or os.PathLike object, not NoneType
[2021-07-29 12:17:12,363] - Sir Perceval completed his quest.
```
Valid token:
```
$ perceval github finbourne lusid-sdk-csharp -t TOKEN > /dev/null
[2021-07-29 12:19:43,038] - Sir Perceval is on his quest.
[2021-07-29 12:19:56,426] - Summary of results

	   Total items: 	102
	Items produced: 	102
	 Items skipped: 	0

	Last item UUID: 	1ca0427f6b5ff2dc4608ffba64772eda5eb4c1b0
	Last item date: 	2021-07-24 20:24:24+00:00

	Min. item date: 	2018-04-18 11:58:31+00:00
	Max. item date: 	2021-07-24 20:24:24+00:00

	Min. offset: 	-	Max. offset: 	-	Last offset: 	-


[2021-07-29 12:19:56,429] - Sir Perceval completed his quest.
```

Best,
Quan

**Comment by mneedham** [comment]
When I try with my token using Perceval - the one I pasted above was made up. See below:

```
% perceval github finbourne lusid-sdk-csharp -t <my-token>  
[2021-07-29 11:31:42,822] - Sir Perceval is on his quest.
{
    "backend_name": "GitHub",
    "backend_version": "0.26.0",
    "category": "issue",
    "classified_fields_filtered": null,
    "data": {
        "active_lock_reason": null,
        "assignee": null,
        "assignee_data": {},
        "assignees": [],
        "assignees_data": [],
        "author_association": "MEMBER",
        "body": "",
        "closed_at": "2018-04-18T11:46:16Z",
        "comments": 0,
        "comments_data": [],
        "comments_url": "https://api.github.com/repos/finbourne/lusid-sdk-csharp/issues/1/comments",
        "created_at": "2018-04-18T11:42:33Z",
        "events_url": "https://api.github.com/repos/finbourne/lusid-sdk-csharp/issues/1/events",
        "html_url": "https://github.com/finbourne/lusid-sdk-csharp/pull/1",
        "id": 315444410,
        "labels": [],
        "labels_url": "https://api.github.com/repos/finbourne/lusid-sdk-csharp/issues/1/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTgyNDUxNzc2",
        "number": 1,
        "performed_via_github_app": null,
        "pull_request": {
            "diff_url": "https://github.com/finbourne/lusid-sdk-csharp/pull/1.diff",
            "html_url": "https://github.com/finbourne/lusid-sdk-csharp/pull/1",
            "patch_url": "https://github.com/finbourne/lusid-sdk-csharp/pull/1.patch",
            "url": "https://api.github.com/repos/finbourne/lusid-sdk-csharp/pulls/1"
        },
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/finbourne/lusid-sdk-csharp/issues/1/reactions"
        },
        "reactions_data": [],
        "repository_url": "https://api.github.com/repos/finbourne/lusid-sdk-csharp",
        "state": "closed",
        "title": "Revert to target .NET Standard 1.1 for compatibility",
        "updated_at": "2018-04-18T11:58:31Z",
        "url": "https://api.github.com/repos/finbourne/lusid-sdk-csharp/issues/1",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/1313357?v=4",
            "events_url": "https://api.github.com/users/steco/events{/privacy}",
            "followers_url": "https://api.github.com/users/steco/followers",
            "following_url": "https://api.github.com/users/steco/following{/other_user}",
            "gists_url": "https://api.github.com/users/steco/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/steco",
            "id": 1313357,
            "login": "steco",
            "node_id": "MDQ6VXNlcjEzMTMzNTc=",
            "organizations_url": "https://api.github.com/users/steco/orgs",
            "received_events_url": "https://api.github.com/users/steco/received_events",
            "repos_url": "https://api.github.com/users/steco/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/steco/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/steco/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/steco"
        },
        "user_data": {
            "avatar_url": "https://avatars.githubusercontent.com/u/1313357?v=4",
            "bio": "Engineer at @finbourne, building LUSID - an open, cloud-native investment data machine that consolidates and synchronises investment data.",
            "blog": "",
            "company": "@finbourne ",
            "created_at": "2012-01-08T18:22:34Z",
            "email": null,
            "events_url": "https://api.github.com/users/steco/events{/privacy}",
            "followers": 1,
            "followers_url": "https://api.github.com/users/steco/followers",
            "following": 0,
            "following_url": "https://api.github.com/users/steco/following{/other_user}",
            "gists_url": "https://api.github.com/users/steco/gists{/gist_id}",
            "gravatar_id": "",
            "hireable": null,
            "html_url": "https://github.com/steco",
            "id": 1313357,
            "location": "London",
            "login": "steco",
            "name": null,
            "node_id": "MDQ6VXNlcjEzMTMzNTc=",
            "organizations": [
                {
                    "avatar_url": "https://avatars.githubusercontent.com/u/22306292?v=4",
                    "description": "",
                    "events_url": "https://api.github.com/orgs/finbourne/events",
                    "hooks_url": "https://api.github.com/orgs/finbourne/hooks",
                    "id": 22306292,
                    "issues_url": "https://api.github.com/orgs/finbourne/issues",
                    "login": "finbourne",
                    "members_url": "https://api.github.com/orgs/finbourne/members{/member}",
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyMzA2Mjky",
                    "public_members_url": "https://api.github.com/orgs/finbourne/public_members{/member}",
                    "repos_url": "https://api.github.com/orgs/finbourne/repos",
                    "url": "https://api.github.com/orgs/finbourne"
                }
            ],
            "organizations_url": "https://api.github.com/users/steco/orgs",
            "public_gists": 0,
            "public_repos": 9,
            "received_events_url": "https://api.github.com/users/steco/received_events",
            "repos_url": "https://api.github.com/users/steco/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/steco/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/steco/subscriptions",
            "twitter_username": null,
            "type": "User",
            "updated_at": "2021-07-28T08:09:06Z",
            "url": "https://api.github.com/users/steco"
        }
    },
    "origin": "https://github.com/finbourne/lusid-sdk-csharp",
    "perceval_version": "0.17.7",
    "search_fields": {
        "item_id": "315444410",
        "owner": "finbourne",
        "repo": "lusid-sdk-csharp"
    },
    "tag": "https://github.com/finbourne/lusid-sdk-csharp",
    "timestamp": 1627554704.563066,
    "updated_on": 1524052711.0,
    "uuid": "53cbe734bbc02dec11c8ba6d3d27d9d48054dad0"
}
```

Are you able to get it working when using the Docker images and if so, what Docker command should I be running?

**Comment by zhquan** [comment]
@mneedham I use [micro.py](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/micro.py) to test and `bitergia/mordred:grimoirelab-0.2.57` (https://hub.docker.com/r/bitergia/mordred) when I use Docker, for more info see https://github.com/chaoss/grimoirelab-sirmordred/tree/master/docker#docker-composeyml

**Comment by sduenas** [comment]
This has been without activity for a month. Feel free to open it if the problem still exists.
