### ISSUE TITLE
error creating index for slack 

### ISSUE THREAD

**Issue by devarshigoswami** [chaoss/grimoirelab#456]
Hi! thanks for taking the time to read this :)
Trying to add slack as a data source in grimoirelab , im running it using docker-compose 

here is what I did 
1. edited conf/projects.json and conf/setup-secured.cfg in modred container

here is how my projects.json looks like 
```
"unknown": {
        "slack":[
            "CHANNEL_ID"
        ]
    }
```

and my setup.cfg

````

[slack]
raw_index = slack
enriched_index = slack_enriched
api-token = API_TOKEN
no-archive = true

````

output for `perceval slack -t API_TOKEN CHANNEL_ID`

````
2021-11-10 11:57:34,690] - Fetching messages of 'CHANNEL' channel from 1970-01-01 00:00:00+00:00
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 618, in run
    for item in big.items:
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 794, in __fetch
    raise e
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 788, in __fetch
    for item in items:
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/slack.py", line 137, in fetch_items
    oldest=oldest, latest=latest)
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/slack.py", line 388, in history
    response = self._fetch(resource, params)
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/slack.py", line 444, in _fetch
    raise SlackClientError(error=result['error'])
perceval.backends.core.slack.SlackClientError: unknown_method

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 169, in <module>
    main()
  File "/usr/local/bin/perceval", line 115, in main
    cmd.run()
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 630, in run
    raise RuntimeError(str(e))
RuntimeError: unknown_method
````
I have not run `docker-compose -f docker-compose-secured.yml -d up` after making changes because its mentioned in this issue that it isn't required if changes are made within the modred container 
https://github.com/chaoss/grimoirelab/issues/332

following are the user token scopes Ive added in the slack bot

![image](https://user-images.githubusercontent.com/55073596/141110375-573d3dee-53dd-4e10-a119-aa39568c017c.png)

Please tell me what am I missing...?

**Comment by zhquan** [comment]
Hi @devarshigoswami 

Sorry for the late reply.

I have no issue using perceval
```
$ perceval slack -t xoxp-aaa CHANNEL_ID --from-date 2022-01-01 > /dev/null                                                                    ─╯
[2022-01-12 10:25:56,338] - Sir Perceval is on his quest.
[2022-01-12 10:25:56,350] - Fetching messages of 'CHANNEL_ID' channel from 2022-01-01 00:00:00+00:00
[2022-01-12 10:25:59,525] - Fetch process completed: 12 message fetched
[2022-01-12 10:25:59,526] - Summary of results

	   Total items: 	12
	Items produced: 	12
	 Items skipped: 	0

	Last item UUID: 	d7ccb844f26d406c70331865e97fe4bdd00710db
	Last item date: 	2022-01-03 07:08:06.000200+00:00

	Min. item date: 	2022-01-03 07:08:06.000200+00:00
	Max. item date: 	2022-01-12 06:31:37.000400+00:00

	Min. offset: 	-	Max. offset: 	-	Last offset: 	-


[2022-01-12 10:25:59,527] - Sir Perceval completed his quest.
```

Some checks:
- The app is installed in your Slack instance.
- The token is correct
- The channel ID is correct
- You are using the latest version of Perceval

I hope it helps you.

Best,
Quan

**Comment by vchrombie** [comment]
Hi @devarshigoswami 

> Some checks:
>     * The app is installed in your Slack instance. 
>     * The token is correct
>     * The channel ID is correct
>     * You are using the latest version of Perceval

Were you able to fix the issue?

**Comment by vchrombie** [comment]
I think the most frequent mistake is we forget to install the app in the slack instance. I faced a similar issue but it got resolved after I added it.

Anyways closing this issue since it doesn't have much activity and I hope it was solved.

@devarshigoswami please let us know and re-open it if needed.
