### ISSUE TITLE
Private GitHub repos unauthorized

### ISSUE THREAD

**Issue by a-romero** [chaoss/grimoirelab#469]
Hi,

I am doing analysis across my organization's repos in Github, which are all private. So far, I've managed to successfully import all the data related to git (ie authors, commits, etc) by using a token and the following projects.json config:

```
{
    "app": {
      "meta": {
        "title": "app"
      },
      "git": [
          "https://organization:******@github.com/organization/my-repo.git"
          ]
    }
}
```

I've tried doing the same for github to get insights about PRs, Issues, etc, but if I use the same config applied to GitHub it fails:

```
{
    "app": {
      "meta": {
        "title": "app"
      },
      "github": [
          "https://organization:******@github.com/organization/my-repo.git"
          ]
    }
}
```
My setup.cfg includes:
```
[github]
api-token = ******
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
```

The error I get when I run it is:

```
2022-02-16 23:34:00,589 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/organization/my-repo.git): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 213, in fetch
    self.client = self._init_client()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 285, in _init_client
    self.archive, from_archive)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 609, in __init__
    self._choose_best_api_token()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 908, in _choose_best_api_token
    self._update_current_rate_limit()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 953, in _update_current_rate_limit
    raise error
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 945, in _update_current_rate_limit
    response = super().fetch(url)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
```

Any ideas as to why the GitHub requests would be unauthorized if the same token works for Git projects? The token has full read access across all scopes.

**Comment by vchrombie** [comment]
Hi @a-romero, thanks for opening an issue.

Good to see that you got the git configurations right and you got it working. If you need more clarification, you can checkout the tutorial https://chaoss.github.io/grimoirelab-tutorial/docs/data-sources/configurations/#git

But, I see a few things wrong with the github configurations tho. As per my understanding, you don't need to add the `username` and `token` to the github url in `projects.json`. Since the token has access to the required scopes, it should be enough to get it working. Also, you can remove the `.git` in the configuration. We ideally use it for using the git backend, not github. So, the corrected configuration should looks something like this
`projects.json`
```
{
   "app":{
      "github":[
         "https://github.com/organization/my-repo"
      ]
   }
}
```
The configurations in `setup.cfg` looks good to me.

Please check the tutorial for more information https://chaoss.github.io/grimoirelab-tutorial/docs/data-sources/configurations/#github

Hope this solves your issue, please let us know.

**Comment by a-romero** [comment]
Just managed to make it work via docker-compose but it somehow doesn't work with the full image using `docker run`.

Thanks for your help.

**Comment by vchrombie** [comment]
> Just managed to make it work via docker-compose but it somehow doesn't work with the full image using `docker run`.

Cool, I didn't know you were using the docker image. Well, I think the docker image is outdated but the docker-compose uses the latest version. So, it is always recommended to use the docker-compose method.

Thanks for finding your way through the issue @a-romero

I will close the issue since we fixed it, please open a new one incase of any other doubt.
