### ISSUE TITLE
Help with debugging github api issues

### ISSUE THREAD

**Issue by brmukum** [chaoss/grimoirelab#477]
Hey team! I'm seeing this error when trying to pull Git data:
```
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RedVentures/acu-docker-sonarqube/issues?state=all&per_page=100&direction=asc&sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00 (Caused by ResponseError('too many 403 error responses'))
2022-03-17 20:22:57,368 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/Company/acue): HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RedVentures/acu-docker-sonarqube (Caused by ResponseError('too many 403 error responses'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 859, in urlopen
```

I can see git commit data but github issues and github pull show nothing even though I have them (github:pull and github:issue etc) set up in the projects.json and setup.cfg.

**Comment by vchrombie** [comment]
Hi @brmukum 
Thanks for reporting the issue, would you mind sharing the configuration files (`projects.json` and `setup.cfg`)?

**Comment by brmukum** [comment]
Hi @vchrombie here is what I have for github:issue and pull in the setup
```
[github:issue]
api-token = ****
raw_index = github_issues_demo_raw
enriched_index = github_issues_demo_enriched
no-archive = true
sleep-for-rate = true
category = issue

[github:pull]
raw_index = github-pull_raw
enriched_index = github-pull_enriched
api-token = ****
category = pull_request
sleep-for-rate = true
no-archive = true
#studies = [enrich_demography:github, enrich_areas_of_code:github]
```

The projects.json  looks like this for one of the projects:
```
"Shared Services": {
    "meta": {
      "title": "Shared Services"
    },
    "git": [
      "https://username:****@github.com/Company/repo",
     ]
    "github:repo": [
      "https://github.com/Company/repo"
      "
    ],
    "github:issue": [
      "https://github.com/Company/repo"
      ```

That's what they look like. I can see git commit but issues and PRs are a problem.

**Comment by vchrombie** [comment]
Hi @brmukum, sorry for reaching out late.
```
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RedVentures/acu-docker-sonarqube/issues?state=all&per_page=100&direction=asc&sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00 (Caused by ResponseError('too many 403 error responses'))
2022-03-17 20:22:57,368 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/Company/acue): HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RedVentures/acu-docker-sonarqube (Caused by ResponseError('too many 403 error responses'))
```

Looks like it is some problem with your internet connection. Can you access github.com from the browser? Do you have any VPN which might be blocking the request?

Please let us know.
Thanks.

**Comment by TieWay59** [comment]
Hello @brmukum, I've received the same error log before when my deployment server has slow access to github.com. I fixed it after changing my cloud server plan. 
As vchrombie suggests, VPN should also help.

**Comment by vchrombie** [comment]
@brmukum were you able to fix the issue?

**Comment by vchrombie** [comment]
Closing this issue because of no recent activity.
@brmukum, please feel free to re-open it if you are still facing the same problem.
