### ISSUE TITLE
Quickstart doersn't work.   Elasticsearch container won't start up

### ISSUE THREAD

**Issue by alberttwong** [chaoss/grimoirelab#613]
Following https://chaoss.github.io/grimoirelab-tutorial/docs/getting-started/setup/ on the latest Mac M2.

All the other containers seem to start.

<img width="1115" alt="Screenshot 2023-10-14 at 9 35 24 AM" src="https://github.com/chaoss/grimoirelab/assets/749093/27fef4d4-43a1-4b46-b94f-ba90815c5f7d">

```
2023-10-14 09:33:48 OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2023-10-14 09:33:48 OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=0
2023-10-14 09:33:51 [2023-10-14T16:33:51,268][WARN ][o.e.b.JNANatives         ] [unknown] unable to install syscall filter: 
2023-10-14 09:33:51 java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:342) ~[elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:617) ~[elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:260) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:113) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:108) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51     at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.8.6.jar:6.8.6]
2023-10-14 09:33:51 [2023-10-14T16:33:51,590][INFO ][o.e.e.NodeEnvironment    ] [0Jn6RqD] using [1] data paths, mounts [[/ (overlay)]], net usable_space [7.2gb], net total_space [58.3gb], types [overlay]
2023-10-14 09:33:51 [2023-10-14T16:33:51,591][INFO ][o.e.e.NodeEnvironment    ] [0Jn6RqD] heap size [1.9gb], compressed ordinary object pointers [true]
2023-10-14 09:33:51 [2023-10-14T16:33:51,592][INFO ][o.e.n.Node               ] [0Jn6RqD] node name derived from node ID [0Jn6RqD7S1KzX3thKPZq1Q]; set [node.name] to override
2023-10-14 09:33:51 [2023-10-14T16:33:51,593][INFO ][o.e.n.Node               ] [0Jn6RqD] version[6.8.6], pid[1], build[oss/docker/3d9f765/2019-12-13T17:11:52.013738Z], OS[Linux/6.4.16-linuxkit/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]
2023-10-14 09:33:51 [2023-10-14T16:33:51,593][INFO ][o.e.n.Node               ] [0Jn6RqD] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-8006026679297028819, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Xms2g, -Xmx2g, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=docker]
2023-10-14 09:33:52 [2023-10-14T16:33:52,369][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [aggs-matrix-stats]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [analysis-common]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [ingest-common]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [ingest-geoip]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [ingest-user-agent]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [lang-expression]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [lang-mustache]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [lang-painless]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [mapper-extras]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [parent-join]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [percolator]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [rank-eval]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [reindex]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [repository-url]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [transport-netty4]
2023-10-14 09:33:52 [2023-10-14T16:33:52,370][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] loaded module [tribe]
2023-10-14 09:33:52 [2023-10-14T16:33:52,371][INFO ][o.e.p.PluginsService     ] [0Jn6RqD] no plugins loaded
2023-10-14 09:33:54 [2023-10-14T16:33:54,857][INFO ][o.e.d.DiscoveryModule    ] [0Jn6RqD] using discovery type [zen] and host providers [settings]
2023-10-14 09:33:55 [2023-10-14T16:33:55,329][INFO ][o.e.n.Node               ] [0Jn6RqD] initialized
2023-10-14 09:33:55 [2023-10-14T16:33:55,329][INFO ][o.e.n.Node               ] [0Jn6RqD] starting ...
2023-10-14 09:33:55 [2023-10-14T16:33:55,565][INFO ][o.e.t.TransportService   ] [0Jn6RqD] publish_address {172.19.0.3:9300}, bound_addresses {0.0.0.0:9300}
2023-10-14 09:33:55 [2023-10-14T16:33:55,584][INFO ][o.e.b.BootstrapChecks    ] [0Jn6RqD] bound or publishing to a non-loopback address, enforcing bootstrap checks
2023-10-14 09:33:55 ERROR: [1] bootstrap checks failed
2023-10-14 09:33:55 [1]: system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk
2023-10-14 09:33:55 [2023-10-14T16:33:55,599][INFO ][o.e.n.Node               ] [0Jn6RqD] stopping ...
2023-10-14 09:33:55 [2023-10-14T16:33:55,744][INFO ][o.e.n.Node               ] [0Jn6RqD] stopped
2023-10-14 09:33:55 [2023-10-14T16:33:55,745][INFO ][o.e.n.Node               ] [0Jn6RqD] closing ...
2023-10-14 09:33:55 [2023-10-14T16:33:55,765][INFO ][o.e.n.Node               ] [0Jn6RqD] closed
```

**Comment by sduenas** [comment]
As far as I know, the Elasticsearch versions that GrimoireLab supports are not available for Mac M2. You should use OpenSearch instead. Try first running ElasticSearch or OpenSearch and see if they work before you try to run GrimoireLab too.
