### ISSUE TITLE
How can I fix the error in sirmordered docker logs? 

### ISSUE THREAD

**Issue by pilgrimage80** [chaoss/grimoirelab#643]
This error prevents the data from coming to the web interface when I run grimoerilab. It causes a no result found error.

2024-03-22 07:08:18,980 - GrimoireLab - sirmordred.task_panels - INFO - Dashboard panels, visualizations: uploaded!
2024-03-22 07:08:18,984 - GrimoireLab - sirmordred.task_panels - INFO - Dashboard menu: uploading for 6 ...
2024-03-22 07:08:19,024 - GrimoireLab - sirmordred.task_panels - INFO - Removing old dashboard menu, if any
2024-03-22 07:08:19,045 - GrimoireLab - sirmordred.task_panels - INFO - Adding dashboard menu
2024-03-22 07:08:19,076 - GrimoireLab - sirmordred.task_panels - INFO - Dashboard menu: uploaded!
2024-03-22 07:08:19,076 - GrimoireLab - sirmordred.sirmordred - INFO - Loading projects
2024-03-22 07:08:19,333 - GrimoireLab - sirmordred.task_projects - INFO - Reading projects data from  /home/grimoire/conf/projects.json
**2024-03-22 07:08:19,334 - GrimoireLab - sirmordred.task_manager - ERROR - [Global tasks] Exception in Task Manager Expecting property name enclosed in double quotes: line 8 column 13 (char 251)**
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sirmordred/task_manager.py", line 98, in run
    task.execute()
  File "/usr/local/lib/python3.8/site-packages/sirmordred/task_projects.py", line 133, in execute
    projects = json.load(fprojects)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 13 (char 251)
Exception in thread Global tasks:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/sirmordred/task_manager.py", line 98, in run
    task.execute()
  File "/usr/local/lib/python3.8/site-packages/sirmordred/task_projects.py", line 133, in execute
    projects = json.load(fprojects)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

**Comment by pilgrimage80** [comment]
cat projects.json
{
    "Yonca": {
            "git": ["https://gitlabtest/tutel/yonca.git"],
            "gitlab:issues": ["https://gitlabtest/tutel/yonca.git"],
            "gitlab:merge": ["https://gitlabtest/tutel/yonca.git"]

            ]
    }


cat setup.cfg
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/grimoire/logs
bulk_size = 100
scroll_size = 100
aliases_file = /home/grimoire/aliases.json

[projects]
projects_file = /home/grimoire/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = nginx
user = root
password = root
port = 8000
path = /identities/api/
ssl = false
database = sortinghat_db
autoprofile = [github, git]
matching = [email,name,username]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true

[panels]
kibiter_time_from = now-90d
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.8.6-3
gitlab-issues = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

#[bugzillarest]
#raw_index = bugzillarest_demo_raw
#enriched_index = bugzillarest_demo_enriched
#no-archive = true

#[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

#[discourse]
#raw_index = discourse_demo_raw
#enriched_index = discourse_demo_enriched
#no-archive = true

#[git]
#raw_index = git_demo_raw
#enriched_index = git_demo_enriched
#latest-items = true
#studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

#[github]
#api-token = <YOUR_API_TOKEN_WHERE>
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
#raw_index = github_demo_raw
#sleep-for-rate = true
#sleep-time = "300"
#enriched_index = github_demo_enriched

[gitlab:issues]
api-token = H4iQWJ_9sB7LG9RndKHL
raw_index = gitlab_issues_demo_raw
enriched_index = gitlab_issues_demo_enriched
no-archive = true
enterprise-url = https://gitlabtest
sleep-for-rate = true

#[gitlab:issue]
#category = issue
#raw_index = gitlab-issues_raw
#enriched_index = gitlab-issues_enriched
#api-token = H4iQWJ_9sB7LG9RndKHL
#sleep-for-rate = true
#no-archive = true (suggested)
#studies = [enrich_onion:gitlab-issue] (optional)

[gitlab:merge]
api-token = H4iQWJ_9sB7LG9RndKHL
raw_index = gitlab_merges_demo_raw
enriched_index = gitlab_merges_demo_enriched
no-archive = true
enterprise-url = https://gitlabtest
category = merge_request
sleep-for-rate = true

#[jira]
#raw_index = jira_demo_raw
#enriched_index = jira_demo_enriched
#no-archive = true

#[pipermail]
#raw_index = pipermail_demo_raw
#enriched_index = pipermail_demo_enriched
#no-verify = true

#[mediawiki]
#raw_index = mediawiki_demo_raw
#enriched_index = mediawiki_demo_enriched
#no-archive = true

#[meetup]
#raw_index = meetup_demo_raw
#enriched_index = meetup_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = "300"

#[stackexchange]
#raw_index = stackexchange_demo_raw
#enriched_index = stackexchange_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[slack]
#raw_index = slack_demo_raw
#enriched_index = slack_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[supybot]
#raw_index = supybot_demo_raw
#enriched_index = supybot_demo_enriched

#[twitter]
#raw_index = twitter_demo_raw
#enriched_index = twitter_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = 300

## studies based on enriched indexes

#[enrich_demography:git]

#[enrich_areas_of_code:git]
#in_index = git_demo_raw
#out_index = git-aoc_demo_enriched

#[enrich_onion:git]
#in_index = git
#out_index = git-onion_demo_enriched
#contribs_field = hash

[enrich_onion:gitlab-issue] # (optional)
in_index = gitlab-issues_enriched
out_index = gitlab-issues-onion_enriched
data_source = gitlab-issues

**Comment by sduenas** [comment]
What's your `project.json` file? It seems you are not using the right urls for gitlab repos.

**Comment by pilgrimage80** [comment]
The repos are as follows.
{
    "Yonca": {
        "git": "https://10.40.22.144/tutel/rehber.git",
        "gitlab:issues": "https://10.40.22.144/tutel/rehber/",
        "gitlab:merge": "https://10.40.22.144/tutel/rehber/"
    }
}

**Comment by pilgrimage80** [comment]
Project.json

{
"Yonca": {
"git": "https://gitlabtest/tutel/yonca.git",
"gitlab:issues": "https://gitlabtest/tutel/yonca/issues",
"gitlab:merge": "https://gitlabtest/tutel/yonca/merge_requests"
}
}

**Comment by zhquan** [comment]
Hi @pilgrimage80 

The projects.json is wrong, you don't need to add `issues` or `merge_requests`. More info at https://github.com/chaoss/grimoirelab-sirmordred?tab=readme-ov-file#gitlab-

Try again using this one:
```
{
    "Yonca": {
        "git": [
            "https://gitlabtest/tutel/yonca.git"
        ],
        "gitlab:issues": [
            "https://gitlabtest/tutel/yonca"
        ],
        "gitlab:merge": [
            "https://gitlabtest/tutel/yonca"
        ]
    }
}
```
