### ISSUE TITLE
Docker-Compose issue "Kibana server is not ready yet"

### ISSUE THREAD

**Issue by Dbz** [chaoss/grimoirelab#663]
When I try the `docker-compose up -d` setup, I run into an issue where localhost says "Kibana server is not ready yet"

If I run the command `docker logs docker-compose-elasticsearch-1` I see an error like this:
```
...
[2024-04-15T22:49:46,864][WARN ][o.e.b.JNANatives         ] [unknown] unable to install syscall filter:
java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
	at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:342) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:617) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:260) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:113) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:108) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.8.6.jar:6.8.6]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.8.6.jar:6.8.6]
...
...
...
[1]: system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk
[2024-04-16T06:59:21,262][INFO ][o.e.n.Node               ] [2A7VWtj] stopping ...
[2024-04-16T06:59:21,374][INFO ][o.e.n.Node               ] [2A7VWtj] stopped
[2024-04-16T06:59:21,375][INFO ][o.e.n.Node               ] [2A7VWtj] closing ...
[2024-04-16T06:59:21,390][INFO ][o.e.n.Node               ] [2A7VWtj] closed
```

Is there a suggestion on what the best course of action is here?

Thank you so much for your help and for creating this software. I am looking forward to using it!

**Comment by sduenas** [comment]
> I fixed this by setting the image for elastic-search to be `image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2-arm64` in the docker-compose file, and then I needed to solve another startup issue with adding the following to the elastic search environment:
> 
> ```
>         - node.name=node-1
>         - cluster.initial_master_nodes=node-1
> ```
> 
> I'm happy to close this issue. Do you want me to update any documentation and create a PR to give back to the community?

Happy to have a PR that fixes this issue!

**Comment by Dbz** [comment]
I'm working on getting it working on my other laptop which is an M2 (vs my M1) and running into some more issues that I will work out before submitting a PR.

**Comment by sduenas** [comment]
If you are able to run it in a M2 that will be so helpful because we don't have that processor on our computers, so we don't have a way to try everything there.

**Comment by loreckc** [comment]
Would 

> I'm working on getting it working on my other laptop which is an M2 (vs my M1) and running into some more issues that I will work out before submitting a PR.

I'm running into the same issues, but on M3. If you find a general fix, I'll happy to test it on M3.

**Comment by AnimiVulpis** [comment]
On my M2 based MacBook I got the example (default) docker compose setup working by changing the `docker-compose/docker-compose.yml` file in the following ways:
- Changing the elasticsearch image to `docker.elastic.co/elasticsearch/elasticsearch:7.17.21-arm64`
- Adding the environment key `discovery.type=single-node`

The complete elasticsearch sections looks now like this:
```yaml
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21-arm64
      command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
      ports:
        - 9200:9200
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms2g -Xmx2g
        - ANONYMOUS_USER=true
```

Further testing would be needed to check if "everything" is really working is expected 🤞🏻
