### ISSUE TITLE
Database not initialise correctly

### ISSUE THREAD

**Issue by Eroyi** [chaoss/grimoirelab#705]
## Mordred:
```
2024-10-23 06:50:02,707 - GrimoireLab - sirmordred.sirmordred - INFO - 
2024-10-23 06:50:02,707 - GrimoireLab - sirmordred.sirmordred - INFO - ----------------------------
2024-10-23 06:50:02,708 - GrimoireLab - sirmordred.sirmordred - INFO - Starting SirMordred engine ...
2024-10-23 06:50:02,708 - GrimoireLab - sirmordred.sirmordred - INFO - ----------------------------
2024-10-23 06:50:02,864 - GrimoireLab - sgqlc.endpoint.requests - ERROR - GraphQL query failed with 1 errors
2024-10-23 06:50:02,865 - GrimoireLab - sgqlc.endpoint.requests - INFO - Error #0 tokenAuth:
2024-10-23 06:50:02,865 - GrimoireLab - sgqlc.endpoint.requests - INFO -    | (1146, "Table 'sortinghat_db.auth_user' doesn't exist")
2024-10-23 06:50:02,865 - GrimoireLab - sgqlc.endpoint.requests - INFO -    -
2024-10-23 06:50:02,865 - GrimoireLab - sgqlc.endpoint.requests - INFO -    | Locations:
2024-10-23 06:50:02,865 - GrimoireLab - sgqlc.endpoint.requests - INFO -    | 0 | mutation {
2024-10-23 06:50:02,865 - GrimoireLab - sgqlc.endpoint.requests - INFO -    |     ----------^
Traceback (most recent call last):
  File "/usr/local/bin/sirmordred", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/sirmordred/bin/sirmordred.py", line 79, in main
    SirMordred(config).start()
  File "/usr/local/lib/python3.9/site-packages/sirmordred/sirmordred.py", line 294, in start
    self.__create_sh_client(self.config)
  File "/usr/local/lib/python3.9/site-packages/sirmordred/sirmordred.py", line 365, in __create_sh_client
    self.client.connect()
  File "/usr/local/lib/python3.9/site-packages/sortinghat/cli/client/client.py", line 128, in connect
    raise SortingHatClientError(msg)
sortinghat.cli.client.client.SortingHatClientError: Authentication error; cause: (1146, "Table 'sortinghat_db.auth_user' doesn't exist")
```

## Sortinghat
```
(1146, "Table 'sortinghat_db.matching_blacklist' doesn't exist")
SortingHat database schema is >= 0.8. Done.
```

------------------------

I transcript the docker-compose into a helm chart and tried to bring up the services, but it seems the databases are not initialising correctly.
MariaDB is fully functioning, and I believe `sortinghat` and `mordred` can connect to it as well, otherwise, it won't be throwing the `table does not exist` error. But somehow the database `sortinghat_db` is empty.

**Comment by sduenas** [comment]
Are you using the default configuration? How did you create `sortinghat_db`?

It seems the authorization tables are not created in `sortinghat_db` database. That might happen if multitenancy is activated for sortinghat or if the database was created in a different way.

**Comment by Eroyi** [comment]
> Are you using the default configuration? How did you create `sortinghat_db`?
> 
> It seems the authorization tables are not created in `sortinghat_db` database. That might happen if multitenancy is activated for sortinghat or if the database was created in a different way.

yeah, I figured it out. `sortinghat_db` was created manually in mariadb CLI. Once I delete the database, sortinghat can take over the creation operation.
