### ISSUE TITLE
Latest grimoirelab/full docker image not working with GitHub Enterprise backends

### ISSUE THREAD

**Issue by filmaj** [chaoss/grimoirelab#99]
I ran the full docker image a couple of months ago on my company's GitHub Enterprise instance. All worked well! I would run the image like so:

```
docker run --name grim -p 127.0.0.1:9200:9200 -p my.secret.ip.address:5601:5601
-v $(pwd)/logs:/logs
-v $(pwd)/es-data:/var/lib/elasticsearch
-v $(pwd)/credentials.cfg:/mordred-override.cfg
-v $(pwd)/projects.json:/projects.json
-t grimoirelab/full
```

... with the following config files:

```
➔ cat credentials.cfg
[github]
api-token = super-secret-i-wont-tell-you
enterprise-url = https://git.corp.adobe.com

[projects]
projects_file = /projects.json

~/src/corp-grimoirelab on master
➔ cat projects.json
{
    "opensource_submission_process": {
        "github": [
            "https://git.corp.adobe.com/OpenSourceAdvisoryBoard/opensource_submission_process"
        ],
        "git": [
            "https://git.corp.adobe.com/OpenSourceAdvisoryBoard/opensource_submission_process"
        ]
    }
}
```

However, I just updated to the latest, and it no longer works. I see authentication errors related to GitHub in the output of the docker command - it looks like grimoire is trying to talk to public GitHub and not my enterprise instance:

```
Starting container: eb226f9c9242
Starting Elasticsearch
[ ok ] Starting Elasticsearch Server:.
Waiting for Elasticsearch to start...
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      -
Elasticsearch started
Starting MariaDB
[ ok ] Starting MariaDB database server: mysqld.
Waiting for MariaDB to start...
tcp6       0      0 :::3306                 :::*                    LISTEN      -
MariaDB started
Starting Kibiter
Waiting for Kibiter to start...
..Kibiter started
Starting Mordred to build a GrimoireLab dashboard
This will usually take a while...
2018-04-02 17:01:33,746 - mordred.task_panels - ERROR - Can not find kibiter version
2018-04-02 17:01:33,747 - mordred.task_panels - ERROR - Can not configure kibiter
Dashboard panels, visualizations: uploading...
Dashboard panels, visualizations: uploaded!
Dashboard menu: uploading...
Dashboard menu: uploaded!
Collection for github: starting...
Collection for git: starting...
2018-04-02 17:01:40,574 - grimoire_elk.arthur - ERROR - Error feeding ocean from github (https://github.com/OpenSourceAdvisoryBoard/opensource_submission_process): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/arthur.py", line 207, in feed_backend
    ocean_backend.feed()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/ocean/elastic.py", line 204, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/ocean/elastic.py", line 213, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 127, in fetch
    self.client = self._init_client()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 218, in _init_client
    self.archive, from_archive)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 355, in __init__
    self._init_rate_limit()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 531, in _init_rate_limit
    raise error
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 525, in _init_rate_limit
    response = super().fetch(url)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 157, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 153, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Collection for github: finished after 00:00:00 hours
Username for 'https://git.corp.adobe.com': Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
48/48 unique identities loaded
Enrichment for github: starting...
Elasticsearch aliases for github: creating...
Elasticsearch aliases for github: created!
Enrichment for github: finished after 00:00:00 hours
Elasticsearch aliases for github: creating...
Elasticsearch aliases for github: created!
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
48/48 unique identities loaded
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
48/48 unique identities loaded
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
48/48 unique identities loaded
```

... with that last bit of the output, from 'feeding ocean' to the end, repeating over and over.

It looks like the `enterprise-url` portion of my `.cfg` file is not being honoured.

(not sure if the `Can not configure kibiter` error is serious or not, let me know if I should file that separately)

Thanks for any help!

**Comment by valeriocos** [comment]
@filmaj thank you for reporting this issue. We will check it and let you know asap.

**Comment by jgbarah** [comment]
Thanks or the detailed report. I think at least a part of the problem is with this line (in the command lines for running the container):

```
-v $(pwd)/credentials.cfg:/mordred-override.cfg
```

In this version of the container, the right line should be:

```
-v $(pwd)/credentials.cfg:/override.cfg
```

This was a recent change, and now I realize the tutorial was not reflecting it. I just fixed it, sorry for causing you a wast of time.

Please, try it this way, and let us know if it works.

**Comment by jgbarah** [comment]
> (not sure if the Can not configure kibiter error is serious or not, let me know if I should file that separately)

Yes, please. I cannot reproduce that. Let's wait, just in case, to see if somehow it is a cascading error from the previous one. But if it does not work after the `/override.cfg` case is fixed, yes please file a new bug report.

**Comment by filmaj** [comment]
Thanks so much for the help @jgbarah ! Changing the credential file binding definitely got rid of the Hungry Ocean bug ;)

As for the kibiter error - it is still there. I assume this is related to why my grimoirelab instance is asking for details on elasticsearch indices, and not displaying any data right away? See screenshot below.

<img width="1668" alt="screen shot 2018-04-03 at 2 32 06 pm" src="https://user-images.githubusercontent.com/52645/38277762-656764fa-374e-11e8-8769-20000da4e308.png">

I don't recall seeing this when I set up grimoire the first time around a few months ago.

And, as always: I am super appreciative of everyone's time and help thus far. I hope to contribute to grimoirelab as soon as I get my bearings! Thank you so much for the hand holding thus far.

**Comment by jgbarah** [comment]
> Thanks so much for the help @jgbarah ! Changing the credential file binding definitely got rid of the Hungry Ocean bug ;)

Great!

> As for the kibiter error - it is still there. I assume this is related to why my grimoirelab instance is asking for details on elasticsearch indices, and not displaying any data right away? See screenshot below.

Yes. Mordred takes care of creating an index and then defining a default index, which is something that must be done before panels can be uploaded. In your case, it seems Mordred is not being able of contacting Kibiter. Would you mind trying the container using a mapping for the Kibiter port to 127.0.0.1, instead of an specific IP address? Just to see if it works the same way it works for me in that case.

> And,  as always: I am super appreciative of everyone's time and help thus  far. I hope to contribute to grimoirelab as soon as I get my bearings!  Thank you so much for the hand holding thus far.

I think I'm going to take note of your comment for our appreciation quotes ;-) Seriously, thanks a lot for helping us to find and solve issues. Of course you're more than welcome to contribute as much as you may want ;-)

**Comment by filmaj** [comment]
> Would you mind trying the container using a mapping for the Kibiter port to 127.0.0.1, instead of an specific IP address? Just to see if it works the same way it works for me in that case.

Looks like you nailed it, that seemed to be the issue with respect to the error:

```
Starting container: 2ae35bd31ced
Starting Elasticsearch
[ ok ] Starting Elasticsearch Server:.
Waiting for Elasticsearch to start...
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      -
Elasticsearch started
Starting MariaDB
[ ok ] Starting MariaDB database server: mysqld.
Waiting for MariaDB to start...
tcp6       0      0 :::3306                 :::*                    LISTEN      -
MariaDB started
Starting Kibiter
Waiting for Kibiter to start...
..Kibiter started
Starting Mordred to build a GrimoireLab dashboard
This will usually take a while...
Kibiter/Kibana: version found is 6.1.0-3
Kibiter/Kibana: configured!
Dashboard panels, visualizations: uploading...
Dashboard panels, visualizations: uploaded!
Dashboard menu: uploading...
Dashboard menu: uploaded!
Collection for github: starting...
Collection for git: starting...
Username for 'https://git.corp.adobe.com': Collection for github: finished after 00:00:00 hours
Loading blacklist...
```

I suppose I could work around this temporarily by putting a proxy in front of mordred (like nginx or something).
